- src/AeFinder.Application.Contracts/Block/Dtos/GetSummariesInput.cs
- src/AeFinder.Application.Contracts/Block/Dtos/SummaryDto.cs
- src/AeFinder.Application.Contracts/Block/IBlockAppService.cs
- src/AeFinder.Application/AeFinderApplicationAutoMapperProfile.cs
- src/AeFinder.Application/Block/BlockAppService.cs
- src/AeFinder.Domain/Entities/Es/SummaryIndex.cs
- src/AeFinder.EntityEventHandler.Core/BlockHandler.cs
- src/AeFinder.HttpApi/Controllers/BlockController.cs
> feat: add get new block height api

- AeFinder.sln
- README.md
- src/AeFinder.Application.Contracts/AeFinderApplicationConsts.cs
- src/AeFinder.Application.Contracts/GraphQL/Dto/GraphQLQueryInput.cs
- src/AeFinder.Application.Contracts/GraphQL/GraphQLInfoCacheItem.cs
- src/AeFinder.Application.Contracts/GraphQL/IGraphQLAppService.cs
- src/AeFinder.Application/GraphQL/GraphQLAppService.cs
- src/AeFinder.HttpApi.Host/AppConfigTemplate/filebeat-template.yml
- src/AeFinder.HttpApi.Host/appsettings.json
- src/AeFinder.HttpApi/Controllers/GraphqlController.cs
- src/AeFinder.Kubernetes/KubernetesOptions.cs
fix: find back aefinder.kubernetes module in solution
feat: graphql request forward api
feat: optimize file beat log processor
fix: read me text
> feat: add graphql request forward api

- README.md
- src/AeFinder.Grains/Grain/BlockPush/BlockPusherInfoGrain.cs
- test/AeFinder.Grains.Tests/BlockPush/BlockPusherInfoGrainTests.cs
Fix push history block cannot be automatically recovered. close #21
> Fix push history block cannot be automatically recover

- .github/workflows/test-with-code-coverage.yml
- src/AeFinder.Application/AeFinder.Application.csproj
- src/AeFinder.EntityEventHandler.Core/AeFinder.EntityEventHandler.Core.csproj
- test/AeFinder.App.Tests/Handlers/SubscribedBlockHandlerTests.cs
- test/AeFinder.Application.Tests/AeFinder.Application.Tests.csproj
- test/AeFinder.Application.Tests/BlockScan/BlockScanAppServiceTests.cs
> feat:add ci

- src/AeFinder.App.Deploy/AeFinder.App.Deploy.csproj
- src/AeFinder.Kubernetes/AeFinder.Kubernetes.csproj
close #40 
1.set app deploy project's package id to 0.0.4
2.set kubernetes project's package id to 0.0.4
> Feature: set package id for app deploy & kubernetes module

- src/AeFinder.Application.Contracts/Apps/AppSyncStateDto.cs
- src/AeFinder.Application.Contracts/Apps/IAppService.cs
- src/AeFinder.Application/AppDeployOptions.cs
- src/AeFinder.Application/Apps/AppService.cs
- src/AeFinder.Application/Subscriptions/SubscriptionAppService.cs
- src/AeFinder.HttpApi/Controllers/AppController.cs
- src/AeFinder.HttpApi/Controllers/SubscriptionController.cs
> Hotfix: Adjust and add the AeFinder App code size configuration

- src/AeFinder.BlockChainEventHandler.Core/Processors/BlockChainDataEventHandler.cs
- src/AeFinder.BlockChainEventHandler.Core/Providers/IBlockGrainProvider.cs
- src/AeFinder.BlockChainEventHandler/AeFinder.BlockChainEventHandler.csproj
- src/AeFinder.BlockChainEventHandler/appsettings.apollo.json
- src/AeFinder.EntityEventHandler/AeFinder.EntityEventHandler.csproj
- src/AeFinder.EntityEventHandler/appsettings.apollo.json
- src/AeFinder.Grains/Grain/Blocks/BlockBranchGrain.cs
- src/AeFinder.Grains/Grain/Blocks/BlockGrain.cs
- src/AeFinder.Grains/Grain/Blocks/IBlockBranchGrain.cs
- src/AeFinder.Grains/Grain/Blocks/IBlockGrain.cs
> Feature: Automatic remove block grain

- src/AeFinder.Kubernetes/ResourceDefinition/DeploymentHelper.cs
> Feature: Set app pod request k8s resource

- AeFinder.sln
- src/AeFinder.App.TestBase/AeFinder.App.TestBase.csproj
- src/AeFinder.App.TestBase/AeFinderAppEntityOptions.cs
- src/AeFinder.App.TestBase/AeFinderAppTestBase.cs
- src/AeFinder.App.TestBase/AeFinderAppTestBaseModule.cs
- src/AeFinder.App.TestBase/AppDataIndexProvider.cs
- src/AeFinder.App.TestBase/ClusterFixture.cs
- src/AeFinder.App.TestBase/LogEventHelper.cs
- src/AeFinder.Application/Subscriptions/SubscriptionAppService.cs
- templates/AeFinderAppTemplate/AppTemplate.sln
- templates/AeFinderAppTemplate/src/AppTemplate/AppTemplate.csproj
- templates/AeFinderAppTemplate/src/AppTemplate/AppTemplateModule.cs
- templates/AeFinderAppTemplate/src/AppTemplate/AppTemplateProfile.cs
- templates/AeFinderAppTemplate/src/AppTemplate/Entities/MyEntity.cs
- templates/AeFinderAppTemplate/src/AppTemplate/GraphQL/AppSchema.cs
- templates/AeFinderAppTemplate/src/AppTemplate/GraphQL/GetMyEntityInput.cs
- templates/AeFinderAppTemplate/src/AppTemplate/GraphQL/MyEntityDto.cs
- templates/AeFinderAppTemplate/src/AppTemplate/GraphQL/Query.cs
- templates/AeFinderAppTemplate/src/AppTemplate/Processors/MyLogEventProcessor.cs
- templates/AeFinderAppTemplate/test/AppTemplate.Tests/AppTemplate.Tests.csproj
- templates/AeFinderAppTemplate/test/AppTemplate.Tests/AppTemplateTestBase.cs
- templates/AeFinderAppTemplate/test/AppTemplate.Tests/AppTemplateTestModule.cs
- templates/AeFinderAppTemplate/test/AppTemplate.Tests/AssemblyInfo.cs
- templates/AeFinderAppTemplate/test/AppTemplate.Tests/Processors/MyLogEventProcessorTests.cs
> Feature: Add the TestBase module for AeFinder App

- src/AeFinder.App/BlockProcessing/IFullBlockProcessor.cs
- src/AeFinder.App/BlockState/AppBlockStateSetProvider.cs
- src/AeFinder.App/BlockState/AppDataIndexProvider.cs
- src/AeFinder.App/Handlers/IVersionUpgradeProvider.cs
- src/AeFinder.App/Handlers/LocalSubscribedBlockHandler.cs
- src/AeFinder.App/Handlers/SubscribedBlockHandler.cs
- src/AeFinder.Sdk/Logging/AeFinderLoggerExtensions.cs
> Feature: Optimize AeFinder App logs

- src/AeFinder.App/BlockState/AppBlockStateChangeProvider.cs
> Feature: Optimize AeFinder App processing performance

- src/AeFinder.App.Host/AeFinderAppHostBaseModule.cs
- src/AeFinder.App/AeFinder.App.csproj
- src/AeFinder.Application/Apps/AppLogService.cs
- src/AeFinder.HttpApi.Host/AeFinderHttpApiHostModule.cs
- src/AeFinder.HttpApi.Host/AppConfigTemplate/filebeat-template.yml
- src/AeFinder.HttpApi.Host/appsettings.json
- src/AeFinder.HttpApi/AeFinderHttpApiModule.cs
- src/AeFinder.Kubernetes/AeFinder.Kubernetes.csproj
- src/AeFinder.Kubernetes/AeFinderKubernetesModule.cs
- src/AeFinder.Kubernetes/KubernetesConstants.cs
- src/AeFinder.Kubernetes/Manager/KubernetesAppManager.cs
- src/AeFinder.Logger/AeFinderLoggerModule.cs
- src/AeFinder.Logger/Entities/AppLogIndex.cs
- src/AeFinder.Logger/ILogService.cs
- src/AeFinder.Logger/LogElasticSearchOptions.cs
- src/AeFinder.Logger/LogElasticSearchService.cs
> Feature: Create alias for app log index

- src/AeFinder.Domain/AeFinder.Domain.csproj
> Fix changing non-concurrent collections issue

- .github/workflows/testnet-package.yaml
- Dockerfile
- src/AeFinder.HttpApi.Host/AeFinder.HttpApi.Host.csproj
- src/AeFinder.Silo/Extensions/OrleansHostExtensions.cs
- src/AeFinder.Silo/appsettings.json
> Feature: Set orleans advertised IP in k8s

- .github/workflows/sonarqube.yaml
> Feature: add github action for sonarqube

- src/AeFinder.Application.Contracts/Apps/IAppService.cs
- src/AeFinder.Application/Apps/AppService.cs
- src/AeFinder.Grains/AeFinderGrainsModule.cs
- src/AeFinder.Grains/Grain/Apps/AppSettingOptions.cs
- src/AeFinder.Grains/Grain/Apps/IOrganizationAppGrain.cs
- src/AeFinder.Grains/Grain/Apps/OrganizationAppGrain.cs
- src/AeFinder.Grains/State/Apps/OrganizationAppState.cs
- src/AeFinder.HttpApi/Controllers/OrganizationUnitsController.cs
> Feature: Add a limit on the number of AeFinder Apps

- .github/workflows/mainnet-package.yaml
> Feature: add workflow for mainnet kubernetes

- src/AeFinder.CodeOps/Validators/Whitelist/IWhitelistProvider.cs
- test/AeFinder.CodeOps.Tests/Validators/Whitelist/WhitelistValidatorTests.cs
> Feature: Improve code check whitelist 

- src/AeFinder.CodeOps/Validators/Whitelist/IWhitelistProvider.cs
- test/AeFinder.CodeOps.Tests/Validators/Whitelist/WhitelistValidatorTests.cs
> Feature: CodeCheck allows all namespaces of AutoMapper

- .github/workflows/testnet-package.yaml
- src/AeFinder.App.Host/AeFinderAppHostModule.cs
- src/AeFinder.App/BlockProcessing/IProcessingStatusProvider.cs
- src/AeFinder.App/BlockState/AppBlockStateInitializationProvider.cs
- src/AeFinder.App/Handlers/SubscribedBlockHandler.cs
- src/AeFinder.Grains/Grain/BlockStates/AppBlockStateSetStatusGrain.cs
- src/AeFinder.Sdk/Processor/LogEventContext.cs
- test/AeFinder.App.Tests/Handlers/SubscribedBlockHandlerTests.cs
> Hotfix: Fixed abnormal synchronization state after AeFinder App restart

- src/AeFinder.CodeOps/Validators/Whitelist/IWhitelistProvider.cs
- test/AeFinder.CodeOps.Tests/Validators/Whitelist/WhitelistValidatorTests.cs
> Feature: Improve the code check whitelist

- .github/workflows/mainnet-package.yaml
- .github/workflows/testnet-package.yaml
- src/AeFinder.App/BlockProcessing/BlockAttachService.cs
- src/AeFinder.App/BlockState/AppDataIndexProvider.cs
- src/AeFinder.App/BlockState/AppStateOptions.cs
- src/AeFinder.App/BlockState/AppStateProvider.cs
- src/AeFinder.Sdk/AeFinder.Sdk.csproj
- templates/AeFinderAppTemplate/src/AppTemplate/AppTemplate.csproj
- templates/AeFinderAppTemplate/test/AppTemplate.Tests/AppTemplate.Tests.csproj
- test/AeFinder.App.Tests/BlockProcessing/BlockAttachServiceUnlinkedTests.cs
- test/AeFinder.App.Tests/BlockProcessing/BlockProcessingServiceTests.cs
- test/AeFinder.App.Tests/MockBlockFilterAppService.cs
> Release v2.13.0

- src/AeFinder.Grains/Grain/BlockPush/BlockPusherGrain.cs
> Feature: Improve block push to avoid missing data

- src/AeFinder.BackgroundWorker/AeFinderBackGroundModule.cs
- src/AeFinder.BackgroundWorker/Options/TransactionRepairOptions.cs
- src/AeFinder.BackgroundWorker/ScheduledTask/TransactionRepairWorker.cs
> Fix: The Index of the transaction is incorrect

- src/AeFinder.App.Deploy/DefaultAppDeployManager.cs
- src/AeFinder.App.Deploy/IAppDeployManager.cs
- src/AeFinder.Application.Contracts/Apps/IAppAttachmentService.cs
- src/AeFinder.Application.Contracts/Apps/IAppDeployService.cs
- src/AeFinder.Application/AeFinder.Application.csproj
- src/AeFinder.Application/Apps/AppAttachmentService.cs
- src/AeFinder.Application/Apps/AppDeployService.cs
- src/AeFinder.Application/BlockScan/BlockScanAppService.cs
- src/AeFinder.Application/Subscriptions/SubscriptionAppService.cs
- src/AeFinder.Application/ZipHelper.cs
- src/AeFinder.HttpApi/Controllers/AppDeployController.cs
- src/AeFinder.HttpApi/Models/UpdateAppDockerImageInput.cs
- src/AeFinder.Kubernetes/KubernetesConstants.cs
- src/AeFinder.Kubernetes/Manager/KubernetesAppManager.cs
- src/AeFinder.Kubernetes/ResourceDefinition/DeploymentHelper.cs
> Feature: Support app pod to roll updates & Unzip the uploaded compressed attachments

- src/AeFinder.App.Host/AeFinder.App.Host.csproj
- src/AeFinder.App.Host/AeFinderAppHostBaseModule.cs
- src/AeFinder.App.Host/OrleansHostExtensions.cs
- src/AeFinder.App.Host/Program.cs
- src/AeFinder.App.Host/appsettings.json
- src/AeFinder.App/AeFinder.App.csproj
- src/AeFinder.App/Handlers/LocalSubscribedBlockHandler.cs
- src/AeFinder.App/Handlers/SubscribedBlockHandler.cs
- src/AeFinder.BlockChainEventHandler.Core/Processors/BlockChainDataEventHandler.cs
- src/AeFinder.EntityEventHandler.Core/AeFinder.EntityEventHandler.Core.csproj
- src/AeFinder.EntityEventHandler.Core/BlockHandler.cs
- src/AeFinder.EntityEventHandler.Core/IBlockIndexHandler.cs
- src/AeFinder.Grains/AeFinder.Grains.csproj
- src/AeFinder.Grains/Grain/BlockPush/BlockPusherGrain.cs
- src/AeFinder.HttpApi/Controllers/GraphqlController.cs
> Feature: aggregate execution time for each service processing blockchain data using OpenTelemetry

- src/AeFinder.Application/ApiOptions.cs
- src/AeFinder.Application/Block/BlockAppService.cs
- src/AeFinder.CodeOps/Validators/Whitelist/IWhitelistProvider.cs
- test/AeFinder.Application.Tests/AeFinderApplicationTestModule.cs
- test/AeFinder.Application.Tests/BlockAppServiceTests.cs
- test/AeFinder.CodeOps.Tests/Validators/Whitelist/WhitelistValidatorTests.cs
> Feature: Replace all api interface paging queries with search after

- src/AeFinder.App.Host/AeFinderAppHostBaseModule.cs
- src/AeFinder.AuthServer/appsettings.json
- src/AeFinder.BackgroundWorker/appsettings.json
- src/AeFinder.BlockChainEventHandler/appsettings.json
- src/AeFinder.EntityEventHandler/appsettings.json
- src/AeFinder.HttpApi.Host/appsettings.json
- src/AeFinder.Silo/Program.cs
- src/AeFinder.Silo/appsettings.json
> Feature: Adjust all service log content formats to JSON format

- src/AeFinder.Domain/AeFinder.Domain.csproj
- src/AeFinder.Domain/Entities/Es/BlockBase.cs
- src/AeFinder.Domain/Entities/Es/LogEventIndex.cs
- src/AeFinder.Domain/Entities/Es/TransactionIndex.cs
> Feature: Optimize the query and write performance of non-shard key indexes in entity mapping

- src/AeFinder.HttpApi.Host/AeFinder.HttpApi.Host.csproj
- src/AeFinder.HttpApi.Host/AeFinderHttpApiHostModule.cs
- src/AeFinder.HttpApi.Host/appsettings.json
> Feature: Limit the API request rate

- src/AeFinder.CodeOps/Validators/Whitelist/IWhitelistProvider.cs
- templates/AeIndexerTemplate/src/AeIndexerTemplate/AeIndexerTemplate.csproj
- templates/AeIndexerTemplate/test/AeIndexerTemplate.Tests/AeIndexerTemplate.Tests.csproj
- test/AeFinder.CodeOps.Tests/Validators/Whitelist/WhitelistValidatorTests.cs
> Feature: AeIndexer supports BigInteger

- src/AeFinder.App.Deploy/DefaultAppDeployManager.cs
- src/AeFinder.App.Deploy/IAppDeployManager.cs
- src/AeFinder.Application/Apps/AppService.cs
- src/AeFinder.Kubernetes/Manager/KubernetesAppManager.cs
- src/AeFinder.Kubernetes/ResourceDefinition/DeploymentHelper.cs
> Feature: Optimize the update mechanism for AeIndexer Pod images, memory, and CPU

- src/AeFinder.App.Deploy/DefaultAppDeployManager.cs
- src/AeFinder.App.Deploy/IAppDeployManager.cs
- src/AeFinder.Application.Contracts/Apps/Dto/AppPodInfoDto.cs
- src/AeFinder.Application.Contracts/Apps/Dto/AppPodsPageResultDto.cs
- src/AeFinder.Application.Contracts/Apps/IAppDeployService.cs
- src/AeFinder.Application/Apps/AppDeployService.cs
- src/AeFinder.Application/Apps/AppService.cs
- src/AeFinder.CodeOps/Validators/Whitelist/IWhitelistProvider.cs
- src/AeFinder.HttpApi/Controllers/AppDeployController.cs
- src/AeFinder.Kubernetes/Adapter/IKubernetesClientAdapter.cs
- src/AeFinder.Kubernetes/Adapter/KubernetesClientAdapter.cs
- src/AeFinder.Kubernetes/KubernetesConstants.cs
- src/AeFinder.Kubernetes/Manager/KubernetesAppManager.cs
- src/AeFinder.Kubernetes/ResourceDefinition/DeploymentHelper.cs
- templates/AeIndexerTemplate/src/AeIndexerTemplate/AeIndexerTemplate.csproj
- templates/AeIndexerTemplate/test/AeIndexerTemplate.Tests/AeIndexerTemplate.Tests.csproj
- test/AeFinder.CodeOps.Tests/Validators/Whitelist/WhitelistValidatorTests.cs
> Release v2.19.0

- src/AeFinder.BackgroundWorker.Core/Options/OrleansDataClearOptions.cs
- src/AeFinder.BackgroundWorker.Core/OrleansDbClearService.cs
- src/AeFinder.BackgroundWorker/appsettings.json
- src/AeFinder.Domain/AeFinder.Domain.csproj
> Feature:Optimize the automatic deletion of unnecessary version history data in AeIndexer

- src/AeFinder.HttpApi.Host/AeFinderHttpApiHostModule.cs
- src/AeFinder.HttpApi/Controllers/GraphqlController.cs
> Feature: Support cross-origin access for APIs serving GraphQL

- src/AeFinder.BackgroundWorker.Core/Options/OrleansDataClearOptions.cs
- src/AeFinder.BackgroundWorker.Core/OrleansDbClearService.cs
- src/AeFinder.BackgroundWorker/appsettings.json
- src/AeFinder.CodeOps/Validators/Whitelist/IWhitelistProvider.cs
- src/AeFinder.Domain/AeFinder.Domain.csproj
- src/AeFinder.HttpApi.Host/AeFinderHttpApiHostModule.cs
- src/AeFinder.HttpApi/Controllers/GraphqlController.cs
- test/AeFinder.CodeOps.Tests/Validators/Whitelist/WhitelistValidatorTests.cs
> Release v2.20.0

- src/AeFinder.App/AeFinderAppModule.cs
- src/AeFinder.App/BlockProcessing/BlockProcessingOptions.cs
- src/AeFinder.App/BlockProcessing/IBlockProcessingService.cs
- src/AeFinder.App/BlockProcessing/IFullBlockProcessor.cs
- src/AeFinder.Application/Metrics/ElapsedTimeRecorder.cs
- test/AeFinder.App.Tests/BlockProcessing/FullBlockProcessorTests.cs
> Feature: Add block processing timeout cancellation logic in AeIndexer

- src/AeFinder.Application.Contracts/ApiTraffic/IApiTrafficService.cs
- src/AeFinder.Application/AeFinderApplicationModule.cs
- src/AeFinder.Application/ApiTraffic/ApiTrafficOptions.cs
- src/AeFinder.Application/ApiTraffic/ApiTrafficProvider.cs
- src/AeFinder.Application/ApiTraffic/ApiTrafficService.cs
- src/AeFinder.Application/ApiTraffic/ApiTrafficWorker.cs
- src/AeFinder.Grains/Grain/ApiTraffic/ApiTrafficGrain.cs
- src/AeFinder.Grains/Grain/ApiTraffic/IApiTrafficGrain.cs
- src/AeFinder.Grains/GrainIdHelper.cs
- src/AeFinder.Grains/State/ApiTraffic/ApiTrafficState.cs
- src/AeFinder.HttpApi.Host/AeFinderHttpApiHostModule.cs
- src/AeFinder.HttpApi/Controllers/ApiTrafficController.cs
- src/AeFinder.HttpApi/Controllers/BlockController.cs
- src/AeFinder.HttpApi/Controllers/GraphqlController.cs
- src/AeFinder.Silo/Extensions/OrleansHostExtensions.cs
- test/AeFinder.Application.Tests/ApiTraffic/ApiTrafficServiceTests.cs
> Feature: Records the monthly Api requests

- src/AeFinder.Application/User/Provider/WalletLoginProvider.ExceptionHandler.cs
- src/AeFinder.Application/User/Provider/WalletLoginProvider.cs
- src/AeFinder.AuthServer/AeFinderAuthServerModule.cs
- src/AeFinder.AuthServer/SignatureGrantHandler.ExceptionHandler.cs
- src/AeFinder.AuthServer/SignatureGrantHandler.cs
> Feature: Use AOP Exception handling in Auth Server

- src/AeFinder.Application/AppResources/AppResourceService.cs
- src/AeFinder.Application/Assets/AssetInitializationOptions.cs
- src/AeFinder.Application/Assets/AssetInitializationService.cs
- src/AeFinder.Application/Assets/AssetService.cs
- src/AeFinder.Application/Subscriptions/SubscriptionAppService.cs
- src/AeFinder.BackgroundWorker.Core/EventHandler/AppAssetChangeHandler.cs
- test/AeFinder.Application.Tests/Assets/AssetServiceTests.cs
> Release v2.24.0

- src/AeFinder.Application.Contracts/AeFinderApplicationConsts.cs
- src/AeFinder.Application.Contracts/Billings/IBillingService.cs
- src/AeFinder.Application.Contracts/User/Dto/OrganizationIndexDto.cs
- src/AeFinder.Application/Billings/BillingService.cs
- src/AeFinder.Application/Merchandises/MerchandiseService.cs
- src/AeFinder.Application/User/Provider/OrganizationInformationProvider.cs
- src/AeFinder.BackgroundWorker.Core/EventHandler/AppCreateHandler.cs
- src/AeFinder.BackgroundWorker.Core/EventHandler/MaxAppCountUpdateHandler.cs
- src/AeFinder.BackgroundWorker.Core/EventHandler/OrganizationUpdateHandler.cs
- src/AeFinder.Domain.Shared/Organizations/OrganizationUnitExtensionUpdateEto.cs
- src/AeFinder.Domain/App/Es/OrganizationIndex.cs
- src/AeFinder.HttpApi/Controllers/BillingController.cs
> Feature: Management api

- src/AeFinder.Application.Contracts/GraphQL/IGraphQLAppService.cs
- src/AeFinder.Application/GraphQL/GraphQLAppService.cs
- src/AeFinder.HttpApi/Controllers/GraphqlController.cs
> Improve GraphQL query performance via Kubernetes Service
